export const CROPS = [
  {
    name: 'Cotton',
    icon: '🌿',
    minTemp: 21,
    maxTemp: 35,
    minRain: 50,
    maxRain: 100,
    minHumidity: 40,
    season: 'Kharif (Jun–Oct)',
    tip: 'Needs well-drained black soil. Avoid waterlogging.',
  },
  {
    name: 'Wheat',
    icon: '🌾',
    minTemp: 10,
    maxTemp: 25,
    minRain: 30,
    maxRain: 70,
    minHumidity: 35,
    season: 'Rabi (Nov–Mar)',
    tip: 'Cool weather needed. Irrigate at crown root stage.',
  },
  {
    name: 'Groundnut',
    icon: '🥜',
    minTemp: 20,
    maxTemp: 33,
    minRain: 50,
    maxRain: 125,
    minHumidity: 40,
    season: 'Kharif (Jun–Sep)',
    tip: 'Sandy loam soil is best. Needs good sunlight.',
  },
  {
    name: 'Cumin',
    icon: '🌱',
    minTemp: 10,
    maxTemp: 30,
    minRain: 20,
    maxRain: 50,
    minHumidity: 30,
    season: 'Rabi (Nov–Feb)',
    tip: 'Dry cool climate preferred. Avoid heavy rain.',
  },
  {
    name: 'Rice',
    icon: '🍚',
    minTemp: 22,
    maxTemp: 35,
    minRain: 100,
    maxRain: 200,
    minHumidity: 60,
    season: 'Kharif (Jun–Nov)',
    tip: 'Needs standing water. Clay soil is ideal.',
  },
  {
    name: 'Mustard',
    icon: '🌼',
    minTemp: 10,
    maxTemp: 25,
    minRain: 25,
    maxRain: 60,
    minHumidity: 35,
    season: 'Rabi (Oct–Feb)',
    tip: 'Cool dry climate. Well-drained loamy soil.',
  },
];

export const COLORS = {
  primary: '#2563EB',
  secondary: '#3B82F6',
  accent: '#F59E0B',
  background: '#F8FAFC',
  card: '#FFFFFF',
  text: '#1E293B',
  subtext: '#64748B',
  border: '#E2E8F0',
  light: '#EFF6FF',
  danger: '#EF4444',
  warning: '#F59E0B',
  info: '#3B82F6',
  success: '#10B981',
};
