// Real Indian Government agriculture schemes — links open official portals.

export const SCHEME_CATEGORIES = ['all', 'income', 'insurance', 'credit', 'irrigation', 'subsidy'];

export const SCHEMES = [
  {
    id: 'pmkisan',
    category: 'income',
    icon: '💰',
    color: '#FFFBEB',
    accent: '#D97706',
    titleKey: 'schemePMKisanTitle',
    descKey: 'schemePMKisanDesc',
    amountKey: 'schemePMKisanAmount',
    eligibilityKey: 'schemePMKisanElig',
    link: 'https://pmkisan.gov.in',
  },
  {
    id: 'pmfby',
    category: 'insurance',
    icon: '🛡️',
    color: '#EFF6FF',
    accent: '#2563EB',
    titleKey: 'schemePMFBYTitle',
    descKey: 'schemePMFBYDesc',
    amountKey: 'schemePMFBYAmount',
    eligibilityKey: 'schemePMFBYElig',
    link: 'https://pmfby.gov.in',
  },
  {
    id: 'kcc',
    category: 'credit',
    icon: '💳',
    color: '#EEF2FF',
    accent: '#4F46E5',
    titleKey: 'schemeKCCTitle',
    descKey: 'schemeKCCDesc',
    amountKey: 'schemeKCCAmount',
    eligibilityKey: 'schemeKCCElig',
    link: 'https://www.nabard.org/content1.aspx?id=572&catid=8&mid=490',
  },
  {
    id: 'pmksy',
    category: 'irrigation',
    icon: '💧',
    color: '#EFF6FF',
    accent: '#0EA5E9',
    titleKey: 'schemePMKSYTitle',
    descKey: 'schemePMKSYDesc',
    amountKey: 'schemePMKSYAmount',
    eligibilityKey: 'schemePMKSYElig',
    link: 'https://pmksy.gov.in',
  },
  {
    id: 'soilhealth',
    category: 'subsidy',
    icon: '🧪',
    color: '#FEF3C7',
    accent: '#D97706',
    titleKey: 'schemeSoilTitle',
    descKey: 'schemeSoilDesc',
    amountKey: 'schemeSoilAmount',
    eligibilityKey: 'schemeSoilElig',
    link: 'https://soilhealth.dac.gov.in',
  },
  {
    id: 'drip',
    category: 'irrigation',
    icon: '🌊',
    color: '#F5F3FF',
    accent: '#8B5CF6',
    titleKey: 'schemeDripTitle',
    descKey: 'schemeDripDesc',
    amountKey: 'schemeDripAmount',
    eligibilityKey: 'schemeDripElig',
    link: 'https://agricoop.nic.in',
  },
  {
    id: 'pmkmy',
    category: 'income',
    icon: '👴',
    color: '#FDF4FF',
    accent: '#9333EA',
    titleKey: 'schemePMKMYTitle',
    descKey: 'schemePMKMYDesc',
    amountKey: 'schemePMKMYAmount',
    eligibilityKey: 'schemePMKMYElig',
    link: 'https://maandhan.in',
  },
  {
    id: 'enam',
    category: 'income',
    icon: '🏪',
    color: '#FFF7ED',
    accent: '#EA580C',
    titleKey: 'schemeENAMTitle',
    descKey: 'schemeENAMDesc',
    amountKey: 'schemeENAMAmount',
    eligibilityKey: 'schemeENAMElig',
    link: 'https://enam.gov.in',
  },
];
